version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
    ports:
      - 80:80
      - 433:433
